apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - clusters:
        selector:
          matchLabels:
            workload: demo-api
  template:
    metadata:
      name: 'envoy-gateway-{{ .name }}'
    spec:
      project: default
      source:
        repoURL: docker.io/envoyproxy
        chart: gateway-helm
        targetRevision: v1.8.1
      destination:
        server: '{{ .server }}'
        namespace: envoy-gateway-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
